spring:
  application:
    name: demo-jpa-relationship
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: qwer
    url: jdbc:postgresql://localhost:4002/jpa_relationship
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false